pipeline {
    agent any
    
    environment {
        GOCACHE = "${WORKSPACE}/.cache/go-build"
        GOPATH = "${WORKSPACE}/.go"
    }

    stages {
        stage('Unit Tests - Backend') {
            agent {
              docker {
                image 'snakee/golang-junit:1.21'
                reuseNode true
              }
            }
            steps {
              dir('bugtracker-backend') {
                 sh '''
                     mkdir -p ${GOCACHE}
                     mkdir -p ${GOPATH}
                     go test -v ./...
                 '''
              }
            }
        }
    }
}