pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'echo Tell me more!'
                sh 'date' 
            }
        }
    }
}
